### ISSUE TITLE
Logger fails with error when called with data param containing circular references

### ISSUE THREAD

**Issue by danwild** [VeliovGroup/Meteor-logger#15] opened 2018-07-02 01:27 UTC
### I'm having an issue:

`Logger.prototype.antiCircular` does not remove circular references correctly, which means log calls with data objects containing circular references fail with error.

e.g. 
```javascript
let a = {};
a.a = a;
log.info('my message', a); // throws errors seen below
```

I have added some tests to this package to check that it is not related to how I'm using the logger (test uses simple object like above), which also fail:
 
```javascript
// LoggerMessage#toString
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at LoggerMessage.toString (packages/ostrio:logger/logger.js:317:74)
    at Tinytest.add.test (packages/local-test:ostrio:logger/logger-tests.js:143:95)
    at TestCase.func (packages/tinytest/tinytest.js:628:5)
    at Promise (packages/tinytest/tinytest.js:403:27)
    at new Promise (<anonymous>)
    at TestCase.run (packages/tinytest/tinytest.js:386:12)
    at TestRun._runTest (packages/tinytest/tinytest.js:482:10)
    at Object.manager.testQueue.queueTask [as task] (packages/tinytest/tinytest.js:548:14)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:872:16)
    at packages/meteor.js:849:12

// LoggerMessage Instance
RangeError: Maximum call stack size exceeded
    at Object.keys.forEach.key (http://localhost:7000/packages/ejson.js?hash=8f5a52821d627c13f03f6c9f8691f2a0bc0831a4:706:26)
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone.v [as clone] (http://localhost:7000/packages/ejson.js?hash=8f5a52821d627c13f03f6c9f8691f2a0bc0831a4:706:18)
    at Object.keys.forEach.key (http://localhost:7000/packages/ejson.js?hash=8f5a52821d627c13f03f6c9f8691f2a0bc0831a4:707:22)
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone.v [as clone] (http://localhost:7000/packages/ejson.js?hash=8f5a52821d627c13f03f6c9f8691f2a0bc0831a4:706:18)
    at Object.keys.forEach.key (http://localhost:7000/packages/ejson.js?hash=8f5a52821d627c13f03f6c9f8691f2a0bc0831a4:707:22)
    at Array.forEach (<anonymous>)
    at Object.EJSON.clone.v [as clone] (http://localhost:7000/packages/ejson.js?hash=8f5a52821d627c13f03f6c9f8691f2a0bc0831a4:706:18)
    at Object.keys.forEach.key (http://localhost:7000/packages/ejson.js?hash=8f5a52821d627c13f03f6c9f8691f2a0bc0831a4:707:22)
```

As it presents in browser:
![image](https://user-images.githubusercontent.com/3774647/42141081-e0bf3eca-7de9-11e8-9e97-193bd9e51dbb.png)

### Versions
- testing `ostrio:logger 2.0.6`.
- issue affects client and server.
- Chrome 65
- OSX 10.12.6

I'll probably put PR up shortly.

**Comment by dr-dimitru** [comment] 2018-07-27 00:09
@danwild thank you a lot for contribution!
Merged and published as [`v2.0.7`](https://github.com/VeliovGroup/Meteor-logger/releases/tag/2.0.7). Let me know how it works on your end.

Feel free to reopen it in case if the issue is still persists on your end.

**Closed as completed by dr-dimitru** 2018-07-27 00:09 UTC

**Comment by danwild** [comment] 2018-07-30 00:55
`2.0.7` works a treat; thanks again @dr-dimitru for the great plugins!

**Comment by dr-dimitru** [comment] 2018-07-30 10:05
@danwild thank you for using and making this package better 👍👨‍💻🎉

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-logger)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/logger)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
