### ISSUE TITLE
Additional action on certain log levels?

### ISSUE THREAD

**Issue by meecect** [VeliovGroup/Meteor-logger#22] opened 2022-09-08 18:29 UTC
I'm using logger console and logger mongo and both work perfectly.  I'd like to send an email with the log message on error and critical levels.  Rather than making a new logging interface, is there a way to execute a function when the log function is called, so that I can inspect the level and perform actions based on the level (like send an email in some cases).

thanks,
Cliff

**Comment by dr-dimitru** [comment] 2022-09-20 11:00
@meecect one of the options I see right away — subscribe to the changes in MongoDB collection and trigger actions based on new entries.

Another one — implement `.on()` hook.

P.S. it's been 12 days, have you found a solution so far?

**Comment by meecect** [comment] 2022-09-21 19:45
I ended up doing something kinda hacky:

```
log._error_orig = log.error;

log.error = function(message, data, userId) {
  var body;
  if (data) {
    if(typeof data == 'string') {
      body = data;
    } else {
      body = JSON.stringify(data,null, "  ");
    }
  } else {
    body = message;
  }
  Meteor.call(
    'sendEmail',
    message,
    body,
  );
  return log._error_orig(message, data, userId);
}
```

I'm not sure what .on() hook you are referring to.  Is there an .on() hook in this project?

**Comment by dr-dimitru** [comment] 2022-09-22 00:01
@meecect I meant implement `.on()` hook is another option to your issue

**Comment by dr-dimitru** [comment] 2022-09-22 00:01
Feel free to close it in case if the issue is solved on your end.

**Closed as completed** 2022-09-22 16:48 UTC
